const Projects = [
	{
		id: "recAGJfiU4CeaV0HL",
		order: 3,
		title: "TRIVIA APP",
		dates: "2022",
		aboutProject: [
			" Purpose and Goal:I wanted to learn how to work with APIs and handling forms in react , and this was the perfect project",
			"General Requirement: The requirement I had in mind is that the website must be fast and responsive, and users should be able to see their total score at the end of the session ",
			"Stack Explanation:  It's mainly built on react, some normal css and styled components too,mainly because it lets you write actual CSS and it's popular. I used react reveal library to the animation,OPENTRIVADB APIs docs is great and easy to understand",
			"Challenges: settings up the urls parameters were bit of a hassle, because of the categories, also randomising answers was quite interesting, i had to do lots of googling",
		],
		project: "trivia app,",
		live: "https://trivia-plus.netlify.app/",
		coderepo: "https://github.com/Jcolejeff/quizApp",
	},
	{
		id: "recIL6mJNfWObonls",
		order: 2,
		title: "MOVIE LOOK-UP",
		dates: "2022",
		aboutProject: [
			"Hashtag drinking vinegar scenester mumblecore snackwave four dollar toast, lumbersexual XOXO. Cardigan church-key pabst, biodiesel vexillologist viral squid.",
			"Franzen af pitchfork, mumblecore try-hard kogi XOXO roof party la croix cardigan neutra retro tattooed copper mug. Meditation lomo biodiesel scenester",
			"Fam VHS enamel pin try-hard echo park raw denim unicorn fanny pack vape authentic. Helvetica fixie church-key, small batch jianbing messenger bag scenester +1",
			"Fam VHS enamel pin try-hard echo park raw denim unicorn fanny pack vape authentic. Helvetica fixie church-key, small batch jianbing messenger bag scenester +1",
		],
		project: "movie look-up,",
		live: "https://movie-look-up.netlify.app",
		coderepo: "https://github.com/Jcolejeff/moive-look-up",
	},
	{
		id: "rec61x18GVY99hQq5",
		order: 1,
		title: "MARVEL COMICS LOOK-UP",
		dates: "2022",
		aboutProject: [
			"I'm baby woke mumblecore stumptown enamel pin. Snackwave prism pork belly, blog vape four loko sriracha messenger bag jean shorts DIY bushwick VHS. Banjo post-ironic hella af, palo santo craft beer gluten-free.",
			"YOLO drinking vinegar chambray pok pok selfies quinoa kinfolk pitchfork street art la croix unicorn DIY. Woke offal jianbing venmo tote bag, palo santo subway tile slow-carb post-ironic pug ugh taxidermy squid.",
			"Pour-over glossier chambray umami 3 wolf moon. Iceland kale chips asymmetrical craft beer actually forage, biodiesel tattooed fingerstache. Pork belly lomo man braid, portland pitchfork locavore man bun prism.",
		],
		project: "marvel api,",
		live: "https://jeffcole-marvel-db.netlify.app",
		coderepo: "https://github.com/Jcolejeff/COMIC-api",
	},
	{
		id: "rec61x18GVY99hQq5",
		order: 1,
		title: "Bookmark Extension",
		dates: "2022",
		aboutProject: [
			"I'm baby woke mumblecore stumptown enamel pin. Snackwave prism pork belly, blog vape four loko sriracha messenger bag jean shorts DIY bushwick VHS. Banjo post-ironic hella af, palo santo craft beer gluten-free.",
			"YOLO drinking vinegar chambray pok pok selfies quinoa kinfolk pitchfork street art la croix unicorn DIY. Woke offal jianbing venmo tote bag, palo santo subway tile slow-carb post-ironic pug ugh taxidermy squid.",
			"Pour-over glossier chambray umami 3 wolf moon. Iceland kale chips asymmetrical craft beer actually forage, biodiesel tattooed fingerstache. Pork belly lomo man braid, portland pitchfork locavore man bun prism.",
		],
		project: "bookmark",
		live: "https://bookmark-ce.netlify.app",
		coderepo: "https://github.com/Jcolejeff/bookmark",
	},
];
export default Projects;
